### ISSUE TITLE
Modifications and updates requested

### ISSUE THREAD

**Issue by vcvpaiva** [own-pt/nomlex-pt#1]
There are two stale links in the documentation.
I  want to know if the file nomlex-pt.rdf still has the 4,240 nominalizations as in the old doc or not.
is there a way of exporting the rdf file as csv file as well?
Thanks

**Comment by arademaker** [comment]
Links updated. We have already discussed the data files. As soon as possible we update the RDF file here.

**Comment by vcvpaiva** [comment]
I would like the tsv file here as well, re-opening the issue.

**Comment by vcvpaiva** [comment]
Alexandre, the links
 http://wnpt.brlcloud.com:10035/repositories/nomlex-br#query/r/total
 http://wnpt.brlcloud.com:10035/repositories/nomlex-br#query/r/provenance
are still stale.

**Comment by arademaker** [comment]
tsv file can be obtained from the query. We can do better in the future if a concrete demands justifty.

**Comment by vcvpaiva** [comment]
I do see the point, as GitHub I can see from anywhere, the triplestore only from home. adding the file.

**Comment by arademaker** [comment]
please don't make it. the blocked access from work is a problem only for you!

**Comment by vcvpaiva** [comment]
ok.but I am the one who does the work.

**Comment by vcvpaiva** [comment]
There's a difference in numbers. 4250 vs 3527 in all-nomlex. why is that?

**Comment by vcvpaiva** [comment]
The difference in numbers has been clarified and missing nomlex pairs will be recovered. I can close the issue now.
