### ISSUE TITLE
query to produce all triples of NomLex-PT?

### ISSUE THREAD

**Issue by vcvpaiva** [own-pt/nomlex-pt#2]
at the moment we only have as pre-computed queries in the endpoint queries that compute "missing or floating" nouns or verbs.

I would like a pre-computed query that produces all triples, as a way of comparison to other lexicons of nominalizations, such as Nomage or Ancora or Dicionário de nomes deverbais (http://www.portaldalinguaportuguesa.org/recursos.html?action=derdict)

**Comment by arademaker** [comment]
In the first page you can click on 'View statements' to browse all 4,526,209 triples. But I don't think that this is what you really want. If you want all nominalizations:

```
PREFIX nomlex: <https://w3id.org/own-pt/nomlex/schema/>

select ?w1 ?w2 ?prov
{
  ?nm a nomlex:Nominalization ;
    nomlex:verb ?w1 ;
    nomlex:noun ?w2 ;
    dc:provenance ?prov .
}
```

The model is changing but this is query will work for now.

**Comment by vcvpaiva** [comment]
yep, I meant all triples relating verbs and their nominalizations, thanks!!!
